version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
      - /mysql-config/my.cnf:/etc/mysql/conf.d
    ports:
      - "3307:3306"
      - "33061:33060"
      
  zeromqasyncmysql:
    build:
      context: .
      dockerfile: Dockerfile.cpp_server
    container_name: zeromqasyncmysql
    networks:
      - app-network
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: paul
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - "5555:5555"
      
  zmqparallel:
    build:
      context: .
      dockerfile: Dockerfile.zmq-parallel
    container_name: zmqparallel
    networks:
      - app-network
    volumes:
      - ./zmq-server:/app
    depends_on:
      - mysql
      - zeromqasyncmysql
    command: php /app/sleep.php   
      
  phpapache:
    build:
      context: .
      dockerfile: Dockerfile.php-apache
    container_name: phpapache
    networks:
      - app-network
    volumes:
      - ./app:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
      - zmqparallel     
      - zeromqasyncmysql

networks:
  app-network:

volumes:
  mysql-data:
